export const CategoryEnum = {
  SLOTS: "slots",
  BLACKJACK: "blackjack",
  ROULETTE: "roulette",
  LIVE: "live",
  BACCARAT: "baccarat",
  CRASH: "crash",
  DICE: "dice",
  VIDEO_POKER: "video-poker",
  BOOKS: "books",
  BONUS_BUY: "bonus-buy",
  FRUITS: "fruits",
  HOT: "hot",
  FEATURED_GAMES: "featured-games",
  NEW_RELEASES: "new-releases",
  HOT_GAMES: "hot-games",
};
